data_sizes: # in bits
  hash_output: 160
  random_number: 160
  ec_point: 320
  timestamp: 32

benchmark:
  iterations: 10  # no. of times to run each exp
  curve_name: 'secp256r1'

network:
  bandwidth_bps: 10000000  # 10 Mbps

cost_formulas: # number of operations per entity
  vehicle:
    hash: 6
    ec_scalar_mult: 2
    ec_point_add: 0
    sym_enc_dec: 0
    bilinear_pairing: 0
  fog_node:
    hash: 11
    ec_scalar_mult: 1
    ec_point_add: 0
    sym_enc_dec: 0
    bilinear_pairing: 0
  cloud_server:
    hash: 11
    ec_scalar_mult: 2
    ec_point_add: 0
    sym_enc_dec: 0
    bilinear_pairing: 0

output:
  results_dir: "evaluation/results"
